[package]
name = "ibc-denom-resolver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-schema = "1.3.1"
cosmwasm-std = { version = "1.3.1", features = ["stargate"] }
serde = "1.0"
serde-json-wasm = "0.5.1"
thiserror = "1.0"
cw-utils = "1.0.1"
cw-storage-plus = "1.1.0"
packet-forward = { path = "../packet-forward" }
